import catalogue from "./catalogue.json";

/**
 * Catalogue data, generated by crawling all 491 legacy khalsa.co.in pages.
 * Shapes mirror the planned Sanity schema, so swapping these accessors for
 * GROQ queries later is a one-file change.
 *
 * Coverage: 398 products, 12 categories, 491 legacy paths mapped.
 * 141 products carry no specification table because the legacy page did not
 * have one either — several were commented out in the original HTML.
 */

export type Spec = { label: string; value: string };

export type Product = {
  code: string;
  slug: string;
  title: string;
  category: string;
  specs: Spec[];
  images: string[];
  legacyPath: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type Category = {
  slug: string;
  title: string;
  group: "play" | "fitness" | "sports" | "surfaces";
  intro: string;
  count: number;
  gallery: string[];
  legacyPaths: string[];
};

export const PRODUCTS = catalogue.products as Product[];
export const CATEGORIES = catalogue.categories as Category[];
export const LEGACY_REDIRECTS = catalogue.legacyRedirects as Record<string, string>;

export const SITE = {
  legalName: "Khalsa Exports Private Limited",
  shortName: "Khalsa",
  founded: 1985,
  tagline: "Igniting the sporting zeal through quality equipment",
  address: {
    street: "88/1 Suraj Kund Road, Near Sati Mandir",
    city: "Meerut",
    region: "Uttar Pradesh",
    postalCode: "250001",
    country: "India",
  },
  phones: ["+91 94122 03943", "+91 93584 02281", "+91 89410 37333"],
  emails: ["infokgw@khalsa.co.in", "infokepl@khalsa.co.in"],
  counters: [
    { value: 40, suffix: "+", label: "Years of continuous manufacture" },
    { value: 27, suffix: "", label: "Certifications held" },
    { value: 14, suffix: "", label: "MSME test reports" },
    { value: PRODUCTS.length, suffix: "", label: "Products in the catalogue" },
  ],
};

export const CERTIFICATIONS = [
  "ISO 9001", "ISO 14001", "ISO 45001", "ISO 50001", "ISO 27001", "ISO 13485",
  "EN 1176-1:2017", "EN 16630", "EN 14904", "CE", "GS", "BIFMA", "GMP", "RoHS",
];

export const TEST_REPORTS = [
  "GI pipe — thickness & coating", "Weld strength", "Bearing load",
  "Powder-coat adhesion", "Salt-spray corrosion", "Impact attenuation",
];

/** The nine photographs fused into one 1600×1600 JPEG on the legacy homepage. */
export const RECOGNITION = [
  { id: "modi", who: "Sh. Narendra Modi", role: "Prime Minister of India",
    what: "Exercising on Khalsa open-gym equipment at a Fit India exhibition.",
    image: "/recognition/modi.jpg", imageColour: "/recognition/modi-colour.jpg" },
  { id: "rajnath", who: "Sh. Rajnath Singh", role: "Defence Minister of India",
    what: "Exercising on Khalsa open-gym equipment during a ministerial visit.",
    image: "/recognition/rajnath.jpg", imageColour: "/recognition/rajnath-colour.jpg" },
  { id: "yogi", who: "Sh. Yogi Adityanath", role: "Chief Minister, Uttar Pradesh",
    what: "Reviewing the Khalsa stand alongside the Prime Minister.",
    image: "/recognition/yogi.jpg", imageColour: "/recognition/yogi-colour.jpg" },
  { id: "lucknow", who: "Khalsa Gym, Lucknow", role: "Municipal installation",
    what: "Inaugurated with the Mayor and the Municipal Commissioner.",
    image: "/recognition/lucknow.jpg", imageColour: "/recognition/lucknow-colour.jpg" },
  { id: "germany", who: "Germany", role: "International trade fair",
    what: "Khalsa Exports equipment presented to export buyers in Europe.",
    image: "/recognition/germany.jpg", imageColour: "/recognition/germany-colour.jpg" },
  { id: "founder", who: "Late Sh. Jagjit Singh", role: "Founder",
    what: "Representing Khalsa at the February 2024 sports fair.",
    image: "/recognition/founder.jpg", imageColour: "/recognition/founder-colour.jpg" },
];

/**
 * Range accents. Colour here is wayfinding, not decoration — across twelve
 * ranges a consistent hue is how someone keeps their place. Every value is
 * >= 4.5:1 on white, so they are safe as text as well as rules.
 */
export const GROUP_ACCENT: Record<Category["group"], { hex: string; ratio: string }> = {
  play: { hex: "#1A5FB4", ratio: "5.8:1" },
  fitness: { hex: "#B3121B", ratio: "6.4:1" },
  sports: { hex: "#146B3A", ratio: "6.0:1" },
  surfaces: { hex: "#8A5A00", ratio: "5.5:1" },
};

export function accentFor(slug: string) {
  const c = CATEGORIES.find((x) => x.slug === slug);
  return c ? GROUP_ACCENT[c.group].hex : "var(--text)";
}

/* ── accessors — swap for GROQ when Sanity lands ── */

export const getCategories = () => CATEGORIES;
export const getCategory = (slug: string) => CATEGORIES.find((c) => c.slug === slug);
export const getProducts = (categorySlug?: string) =>
  categorySlug ? PRODUCTS.filter((p) => p.category === categorySlug) : PRODUCTS;
export const getProduct = (categorySlug: string, slug: string) =>
  PRODUCTS.find((p) => p.category === categorySlug && p.slug === slug);
export const getRelated = (p: Product, limit = 4) =>
  PRODUCTS.filter((x) => x.category === p.category && x.slug !== p.slug).slice(0, limit);

/** Categories that carry products, for nav and listing pages. */
export const getStockedCategories = () => CATEGORIES.filter((c) => c.count > 0);
